CREATE TABLE human (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  health INTEGER NOT NULL
);

CREATE TABLE crew (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  capital INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE crew_composition (
  crew_id INTEGER,
  human_id INTEGER UNIQUE,
  role TEXT DEFAULT NULL
);

CREATE TABLE spaceship (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  capacity INTEGER NOT NULL DEFAULT 0,
  reliability INTEGER DEFAULT 0,
  cost INTEGER,
  flight_distance INTEGER
);

CREATE TABLE crew_of_spaceship (
  crew_id INTEGER UNIQUE,
  spaceship_id INTEGER UNIQUE
);

CREATE TABLE planet (
  name TEXT PRIMARY KEY,
  reliability INTEGER DEFAULT 0
);

CREATE TABLE planet_distance (
  name1 TEXT,
  name2 TEXT,
  distance INTEGER,
  UNIQUE (name1, name2)
);

CREATE TABLE spaceship_on_planet (
  id INTEGER UNIQUE,
  name TEXT
);

ALTER TABLE crew_composition ADD FOREIGN KEY (crew_id) REFERENCES crew (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE crew_composition ADD FOREIGN KEY (human_id) REFERENCES human (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE crew_of_spaceship ADD FOREIGN KEY (crew_id) REFERENCES crew (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE crew_of_spaceship ADD FOREIGN KEY (spaceship_id) REFERENCES spaceship (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE planet_distance ADD FOREIGN KEY (name1) REFERENCES planet (name) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE planet_distance ADD FOREIGN KEY (name2) REFERENCES planet (name) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE spaceship_on_planet ADD FOREIGN KEY (id) REFERENCES spaceship (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE spaceship_on_planet ADD FOREIGN KEY (name) REFERENCES planet (name) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE VIEW spaceship_can_land_planet AS SELECT planet.name as planet_name, spaceship.name as spaceship_name FROM planet, spaceship
WHERE planet.reliability < spaceship.reliability
AND spaceship.id NOT IN (
  SELECT id FROM spaceship_on_planet WHERE spaceship_on_planet.name = planet.name
) 
AND spaceship.flight_distance >= (
  SELECT distance FROM planet_distance WHERE planet_distance.name1 = (
    SELECT name FROM spaceship_on_planet WHERE spaceship_on_planet.id = spaceship.id
  ) 
  AND planet_distance.name2 = planet.name AND planet_distance.distance <= spaceship.flight_distance)
;